name: powersupply
description: "Power Supply Meter Reading App - Developed by Babu Saheb"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Image picker and permissions
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.15.1
  permission_handler: ^11.3.1

  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.4
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  retry: ^3.1.0
  http: ^1.2.2
  dio: ^5.7.0
  http_parser: ^4.0.2
  image: ^4.0.17
  path_provider: ^2.1.1
  path: ^1.8.3
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.0
  # flutter_google_places_sdk: ^0.4.3  # Temporarily disabled due to Android compilation error
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_quill: ^11.5.0
  flutter_painter_v2: ^2.1.0+1
  loading_animation_widget: ^1.2.0
  flutter_native_ocr: ^0.1.0
  image_cropper: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_logo.png"
  remove_alpha_ios: true
  background_color: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/splash_Screen.png

  android_12:
    color: "#FFFFFF"
    image: assets/icon/app_logo.png